#!/usr/bin/python3
from sys import argv


def factorize(num):
    
    i = 2

    if num < 2:
        return
    
    while (num % i):
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(num, num / i, i))

if len(argv) != 2:
    exit(1)

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            num = int(line.split('\n')[0])
            factorize(num)
            line = file.readline()
except:
    pass
